---
abstract: 'Twitter Auth for Nephia-apps.'
author:
  - 'ytnobody <ytnobody@gmail.com>'
build_requires:
  Test::More: 0.98
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.5.3, CPAN::Meta::Converter version 2.131560'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Nephia-Plugin-Auth-Twitter
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
provides:
  Nephia::Plugin::Auth::Twitter:
    file: lib/Nephia/Plugin/Auth/Twitter.pm
    version: 0.01
requires:
  Data::UUID::MT: 0
  Nephia::DSLModifier: 0
  Net::Twitter::Lite::WithAPIv1_1: 0
  perl: 5.008005
resources:
  bugtracker: https://github.com/ytnobody/Nephia-Plugin-Auth-Twitter/issues
  homepage: https://github.com/ytnobody/Nephia-Plugin-Auth-Twitter
  repository: git://github.com/ytnobody/Nephia-Plugin-Auth-Twitter.git
version: 0.01
